### ISSUE TITLE
Importing DuW_X2_flows.json in Node-Red - missing pieces

### ISSUE THREAD

**Issue by valueerrorx** [mliebl73/DrexelWeiss_x2#1]
First of all: thx for putting your configuration at github! this way i have something to study :-)

In order to import your flow in Node-Red i need to install additional nodes.
Unfortunately i was not able to figure out what package i need to install in order to get your "ha-button" or "ha-config-entity" and so on..

(node-red-contrib-home-assistant-llat contains some of the missing nodes)

i was not able to get your setup up and running :(

**Comment by mliebl73** [comment]
the packages to install are the node-red-contrib-home-assistant-websocket and the node-red-node-serialport

let me know if that works - I am new to Node-Red ;)

**Comment by valueerrorx** [comment]
thank your for the quick answer (i'm new to all of this ;-) )

**node-red-contrib-home-assistant-websocket** was the missing piece for node-red
https://flows.nodered.org/node/node-red-contrib-home-assistant-websocket

when opening the node configuration it says i also need to install this custom componend in my homeassistant 
https://github.com/zachowj/hass-node-red
(which i just did)   now lets see where this leads to ;-)
